name: Max Elman
favicon: null
layout_spectrum: 0.8639782257378101
typography_spectrum: 0.5555323753505945
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#91908e'
    - '#5c5c5d'
    - '#21121f'
    - '#453f45'
    - '#c8c7d9'
  brandStrength: 0.3847000999376178
  lightness: 0.10147189744748175
  saturation: 0.6270217755809426
  rhythmicContrast: 0.75
purpose: []
